[
    {"id":1,
     "name":"Royli Salon and Studio",
     "email":"roylisalon&studio@gmail.com",
     "phone":"+92 51-2656111",
     "address":"Unit # 6, Juniper Arcade Plaza, School Road, F-6 Super Market, Islamabad, Pakistan",
     "gender":"Female",
     "rating":4.7,
     "img": '../../../assets/salon1.png'},
    {"id":2,
     "name":"Omni Health and Beauty Center",
     "email":"omnih&bcenter@gmail.com",
     "phone":"+92-51 8354422",
     "address":"House 33, Street 3, F-8/3, Islamabad.",
     "gender":"Male & Female",
     "rating":3.4,
     "img":'../../../assets/salon2.png'},
     {"id":3,
      "name":"Maisha Spa and Health Club",
      "email":"manishaspaclub@yahoo.com",
      "phone":"+92 51-2874000",
      "address":"Serena Hotel, Khayaban-e-Suhrawardy, Islamabad.",
      "gender":"Female",
      "rating":3.9,
      "img":'../../../assets/salon3.png'},
      {"id":4,
      "name":"Michael K. Salon",
      "email":"michael.k.salon@gmail.com",
      "phone":"+92-51 28518882",
      "address":"House 1A, Street 22 F-7/2 Islamabad",
      "gender":"Male & Female",
      "rating":4.8,
      "img":'../../../assets/salon4.png'},
      {"id":5,
        "name":"Allure Salon and Spa",
        "email":"alluresalon&spa@hotmail.com",
        "phone":"+92 51-2370345",
        "address":"House # 276 A? Sumbal Rd, F-10/4 F 10/4 F-10, Islamabad.",
        "gender":"Female",
        "rating":4.2,
        "img":'../../../assets/salon5.jpeg'},
        {"id":6,
        "name":"Faizas",
        "email":"faizassalonisb@gmail.com",
        "phone":"+92-51-2353572",
        "address":"8-11 AAA Plaza G-10 Markaz Islamabad",
        "gender":"Female",
        "rating":4.0,
        "img":'../../../assets/salon6.jpeg'},
        {"id":7,
            "name":"Toni and Guy",
            "email":"toni&guyisb@hotmail.com",
            "phone":"+92 51 2814080",
            "address":"2nd floor, Beverly Center, Jinnah Avenue, Islamabad.",
            "gender":"Male & Female",
            "rating":4.8,
            "img":'../../../assets/salon7.jpeg'},
            {"id":8,
            "name":"Sobia salon and studio",
            "email":"sobiasalon&studio322@gmail.com",
            "phone":"+92-51-2655166",
            "address":"M-13, Emirates Building Jinnah Super F-7 Islamabad",
            "gender":"Female",
            "rating":4.6,
            "img":'../../../assets/salon8.jpeg'},
      
    ]